template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "Undefined"
__REPO__ = "lang-zxx"
__UND2C__ = "zxx"
__UNDEFINED__ = "No linguistic content"
__UND__ = "zxx"
