template = "https://github.com/giellalt/template-lang-und"
rev_id = 263
template_sha = "1bc24707891f274cd9b2690b032d9864fa1205f5"

[replacements]
__GLOTTOLOG_ID__ = "Undefined"
__REPO__ = "lang-zxx"
__UND2C__ = "zxx"
__UNDEFINED__ = "No linguistic content"
__UND__ = "zxx"
